version: '3.7'

networks:
  spsnet:


volumes:
  setup:
    driver: local
  elasticsearch:
    driver: local
  sps-pg-main:
    driver: local
  sps-pg-pgadmin:
    driver: local

services:

  # Postgres
  sps-pg-main:
    profiles:
      - sps
      - infrastructure
    image: postgres:latest
    volumes:
      - sps-pg-main:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - spsnet
  
  sps-pg-pgadmin:
    profiles:
      - sps
      - infrastructure
    image: dpage/pgadmin4
    volumes:
      - sps-pg-pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5430:80"
    networks:
      - spsnet

  # Hashicorp Vault
  sps-vault:
    profiles:
      - sps
      - infrastructure
    image: vault:latest
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_TOKEN: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
    ports:
      - 8200:8200
    networks:
      - spsnet

  sps-vault-setup:
    profiles:
      - sps
      - infrastructure
    image: vault:latest
    entrypoint: /bin/sh
    volumes:
      - './vault:/vault-source'
    environment:
      VAULT_ADDR: 'http://sps-vault:8200'
      VAULT_SOURCE_DIR: '/vault-source'
      VAULT_TOKEN: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
    command: >
      -c " sleep 2; /vault-source/vault-init.sh; "
    networks:
      - spsnet
    depends_on:
      - sps-vault

  # Config Server
  sps-config-server:
    profiles:
      - sps
      - infrastructure
    build:
      context: config-server/
      args:
        CONFIG_USER: ${CONFIG_USER:-}
        CONFIG_PASS: ${CONFIG_PASS:-}
        CONFIG_GIT_REPO: ${CONFIG_GIT_REPO:-}
        CONFIG_VAULT_URI: 'http://sps-vault:8200'
        CONFIG_VAULT_TOKEN: ${VAULT_DEV_ROOT_TOKEN_ID:-}
    environment:
      SPRING_SECURITY_USER_NAME: ${CONFIG_USER:-}
      SPRING_SECURITY_USER_PASSWORD: ${CONFIG_PASS:-}
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: ${CONFIG_GIT_REPO:-}
      SPRING_CLOUD_CONFIG_SERVER_VAULT_URI: 'http://sps-vault:8200'
      SPRING_CLOUD_CONFIG_SERVER_VAULT_HOST: 'sps-vault'
      SPRING_CLOUD_CONFIG_SERVER_VAULT_TOKEN: ${VAULT_DEV_ROOT_TOKEN_ID:-}
    ports:
      - 8888:8888
    networks:
      - spsnet
    depends_on:
      - sps-vault

  # Eureka server
  sps-service-registry:
    profiles:
      - sps
      - infrastructure
    build:
      context: service-registry/
    ports:
      - 8761:8761
    networks:
      - spsnet

  # Business logic services
  sps-bff-service:
    profiles:
      - sps
      - business
    build:
      context: services/sps-bff/
    restart: on-failure
    depends_on:
      - sps-config-server
      - sps-service-registry
      - logstash
    environment:
      EUREKA_URI: ${EUREKA_URI:-}
      LOGSTASH_URI: ${LOGSTASH_URI:-}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-}
      SPRING_CLOUD_CONFIG_ENABLED: 'true'
      SPRING_CONFIG_IMPORT: configserver:http://sps-config-server:8888
      SPRING_CLOUD_CONFIG_USERNAME: ${CONFIG_USER:-}
      SPRING_CLOUD_CONFIG_PASSWORD: ${CONFIG_PASS:-}
    ports:
      - 18000:18000
    networks:
      - spsnet

  sps-accounts-service:
    profiles:
      - sps
      - business
    build:
      context: services/sps-accounts/
    restart: on-failure
    depends_on:
      - sps-config-server
      - sps-service-registry
      - logstash
    environment:
      EUREKA_URI: ${EUREKA_URI:-}
      LOGSTASH_URI: ${LOGSTASH_URI:-}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-}
      SPRING_CLOUD_CONFIG_ENABLED: 'true'
      SPRING_CONFIG_IMPORT: configserver:http://sps-config-server:8888
      SPRING_CLOUD_CONFIG_USERNAME: ${CONFIG_USER:-}
      SPRING_CLOUD_CONFIG_PASSWORD: ${CONFIG_PASS:-}
    ports:
      - 18081:18081
    networks:
      - spsnet

  sps-transactions-service:
    profiles:
      - sps
      - business
    build:
      context: services/sps-transactions/
    restart: on-failure
    depends_on:
      - sps-config-server
      - sps-service-registry
      - logstash
    environment:
      EUREKA_URI: ${EUREKA_URI:-}
      LOGSTASH_URI: ${LOGSTASH_URI:-}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-}
      SPRING_CLOUD_CONFIG_ENABLED: 'true'
      SPRING_CONFIG_IMPORT: configserver:http://sps-config-server:8888
      SPRING_CLOUD_CONFIG_USERNAME: ${CONFIG_USER:-}
      SPRING_CLOUD_CONFIG_PASSWORD: ${CONFIG_PASS:-}
    ports:
      - 18080:18080
    networks:
      - spsnet

  # This task is only performed during the *initial* startup of the stack. On all
  # subsequent runs, the service simply returns immediately, without performing
  # any modification to existing users.
  elksetup:
    profiles:
      - sps
      - infrastructure
    build:
      context: elk/setup/
      args:
        STACK_VERSION: ${STACK_VERSION}
    init: true
    volumes:
      - setup:/state:Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - spsnet
    depends_on:
      - elasticsearch

  elasticsearch:
    profiles:
      - sps
      - infrastructure
    build:
      context: elk/elasticsearch/
      args:
        STACK_VERSION: ${STACK_VERSION}
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      CLUSTER_NAME: ${CLUSTER_NAME}
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - spsnet

  logstash:
    profiles:
      - sps
      - infrastructure
    build:
      context: elk/logstash/
      args:
        STACK_VERSION: ${STACK_VERSION}
    volumes:
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - spsnet
    depends_on:
      - elasticsearch

  kibana:
    profiles:
      - sps
      - infrastructure
    build:
      context: elk/kibana/
      args:
        STACK_VERSION: ${STACK_VERSION}
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - spsnet
    depends_on:
      - elasticsearch
