server:
  port: 18000

spring:
  application:
    name: sps-bff
  cloud:
    config:
      enabled: false
      failFast: true

# Eureka config properties
eureka:
  client:
    enabled: true
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true

# Feign clients config properties
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: basic

# Logging level config properties
logging:
  level:
    com.sps.spsbff: INFO
    com.sps.spsbff.clients: DEBUG