server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: core
  cloud:
    config:
      enabled: false
      failFast: true

# Eureka config properties
eureka:
  client:
    enabled: true
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true